services:
  app:
    container_name: api_redis
    ports:
      - 5050:5050
    build:
      context: .
      dockerfile: dockerfile

    restart: always
    volumes:
      - ./:/app
      - /app/.venv/ # Không lấy thư mụv .venv ra ngoài
