[project]
name = "login-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "pydantic>=2.11.5",
    "redis>=6.2.0",
]
